baseURL = "https://3uph.github.io/"
languageCode = "en"
title = "3uph's web page"
theme = "congo"

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  mainSections = ["posts"]
  colorScheme = "auto"
  enableCodeCopy = true
  showReadingTime = true
  toc = true
  breadcrumb = true
  customCSS = ["css/custom.css"]
  [params.homepage]
    showRecent = true
    recentLimit = 8
    showSectionCards = true

